### PR TITLE
bugfix

### PR DESCRIPTION
**Pull request by gicking**
as mailed, with this bugfix write, sector and mass erase work for the 3 boards I have currently available (128k_v2.1, 32k_v1.2 and 32k_v1.3). Please see Bootloader_Overview.ods for details

### CODE REVIEW

**Review by basilhussain — CHANGES_REQUESTED** [review]
For the makefile change, having given it some thought, I think it would be better to not set executable permissions on the script every time it's run, but instead just run the script by calling awk with a command line parameter: `awk -f check-seg-size.awk ...`.

For the changes to common.c, is this to fix the compiler warnings? IIRC, those are from a bug in SDCC - they are spurious and shouldn't really occur. My preferred way to avoid them is to instead explicitly make the constant unsigned - e.g. `(1U << FLASH_CR2_ERASE)` - rather than add a cast.

**Comment by gicking** [comment]
1) changed Makefile as proposed
2) replacing 1 by 1U makes no difference, I still get a warning. Seems to be caused by ~ operator. But I removed the typecast anyway, as it was only to avoid a warning

PS: do you already see the new changes? I am not very familiar with Github...

**Comment by basilhussain** [comment]
Hmm, that's weird that the `1U` change doesn't make any difference. I do that on several other projects and it works there. Also, I just noticed I'm a dumbass and totally missed putting the bitshifts in `flash_block_prg_enable()` and `flash_block_prg_option_wr_enable()`! Can't believe I didn't spot that until now. That might explain why things didn't seem to work until now. :-)

**Comment by gicking** [comment]
as the warnings for commons.c only appear in lines with ~(), I assume the reason is not 1 vs. 1U but the ~ operator

PS: as it has no impact on code size, I reverted to the original (and ignore the warnings)

**Comment by basilhussain** [comment]
I found the report of the original SDCC bug: https://sourceforge.net/p/sdcc/bugs/2733/.

Basically, when an assignment of an expression that evaluates to a constant value is made to a `uint8_t` (or `unsigned char`), at some point in the evaluation of the expression the value is interpreted as a signed `char` and the "overflow in implicit constant conversion" warning is produced. So, basically, any value where bit 7 is set triggers the warning.

I'm still puzzled as to why using `1U` doesn't fix it. I went back and checked a previous project where I do that, and it definitely compiles without such warnings, even though I'm definitely making assignments to 8-bit registers with bit 7 set.

**Comment by gicking** [comment]
strange! But I think it is not quite as straiightforward. Because for the following code

    void main(void) {
      volatile unsigned char x;
      x = ~(1U<<0);
      x = ~(1U<<7);
      x = 0x80;
    }

only the 1st assignment throws "warning 158: overflow in implicit constant conversion". So yes, it seems to be related to bit 7, but only in combination with ~. So probably you are correct, but IMHO the bit 7 bug is in the handling of ~

**Pull request merged**
